repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        types: [python]
        language: python
      - id: flynt
        name: flynt
        entry: flynt
        args: [--fail-on-change]
        types: [python]
        language: python
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        exclude: node_modules
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
        exclude: .serverless,node_modules
      - id: bandit
        name: bandit
        entry: bandit
        language: python
        types: [python]
        args:  [--ini, .bandit, --recursive, src,tests]
      - id: mypy
        name: mypy
        entry: mypy
        types: [python]
        language: python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: end-of-file-fixer
        exclude: .*(min.js|min.css|html|svg|css.map|js.map)
      - id: trailing-whitespace
